install:
  - wget -O hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.45.1/hugo_0.45.1_Linux-64bit.tar.gz
  - tar xvfz hugo.tar.gz
  - rm -rf public

script:
  - ./hugo version
  - ./hugo
  - echo "joshua.bjorkang.family" >> CNAME

deploy:

  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: code
