install:
  - wget -O hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz
  - tar xvfz hugo.tar.gz
  - rm -rf public

script:
  - ./hugo version
  - ./hugo


deploy:

  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  target_branch: master
  on:
    branch: code
