# Site settings
baseURL = "https://joshua.bjorkang.family" 
languageCode = "en-US"
title = "Joshua Björkäng - DevOps Consultant"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2018 Joshua Björkäng"

[params]

  # Metadata for search engines and social sharing
  author = "Joshua Björkäng"
  description = "DevOps Consultant based in Gothenburg, Sweden."
  shareImage = "images/social.jpg"
  twitterHandle = "jbjorkang"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/profile.jpg"
      position = "center center"

  # Links
  #

  # Links List #2
  [[params.links]]
    [params.links.list1]
      heading = "Social"

      [[params.links.list1.link]]
        text = "Twitter"
        url = "https://twitter.com/jbjorkang"
      
       [[params.links.list1.link]]
         text = "Mastodon"
         url = "https://mastodon.technology/@jbjorkang"

      [[params.links.list1.link]]
        text = "Github"
        url = "https://github.com/avantgardefuselage"

    # Links List #1
    [[params.links]]
      [params.links.list2]
        heading = "Connect"

         [[params.links.list2.link]]
           text = "Blog"
           url = "/blog"

        [[params.links.list2.link]]
          text = "Email"
          url = "mailto:j.bjorkang@pm.me"
